import type { CaseEnvelope, ProgressSnapshot } from "@/lib/types/case";

export const MOCK_CASE: CaseEnvelope = {
  caseId: "RL-00427",
  profileId: "PR-01831",
  status: "ok",
  intent: {
    journey: "find_better_job_abroad",
    confidence: 0.88,
    reasoning:
      "Target country and a specific target role were provided with a salary premium objective.",
  },
  profile: {
    profileId: "PR-01831",
    currentCountry: "IN",
    targetCountries: ["DE", "NL"],
    role: "Senior Backend Engineer",
    roleCategory: "software_engineering",
    yearsExperience: 7,
    experienceLevel: "senior",
    currentSalary: { amount: 48000, currency: "USD" },
    targetSalary: { amount: 92000, currency: "USD" },
    familyStatus: "couple",
    urgency: "6m",
    visaStatus: "none",
    budgetCeiling: { amount: 18000, currency: "USD" },
    workPreference: "hybrid",
    relocationWillingness: 0.85,
    priority: "stability",
  },
  summary: {
    caseId: "RL-00427",
    verdict: "go_with_caveats",
    headline:
      "Berlin is feasible within six months — document readiness is the primary gating risk.",
    heroMetrics: [
      { label: "Overall readiness", value: "74", tone: "positive" },
      { label: "Monthly surplus", value: "+ $1,640", tone: "positive" },
      { label: "Runway", value: "14 mo", tone: "neutral" },
      { label: "Documents ready", value: "61 %", tone: "warning" },
    ],
    topWarnings: [
      "Passport expires within 8 months of target move date.",
      "Degree certificate requires apostille for Germany; not yet initiated.",
      "Rental market in Berlin currently favours tenants with local deposit history.",
    ],
    nextActions: [
      "Begin passport renewal within the next two weeks.",
      "Request apostille for bachelor's degree transcript.",
      "Shortlist three EU Blue Card-eligible roles by end of month.",
    ],
    narrative:
      "Your profile supports an EU Blue Card path to Germany within six months. Salary and affordability clear with a healthy monthly surplus, and your role matches strong German demand. The main risks are document-side: a renewing passport and an un-apostilled degree. Addressing those early keeps the timeline intact.",
    degraded: false,
    generatedAt: new Date().toISOString(),
  },
  modules: {
    jobs: {
      status: "ok",
      score: 0.82,
      summary:
        "Strong alignment with EU Blue Card-eligible backend roles in Berlin and Amsterdam.",
      confidence: 0.86,
      totalConsidered: 162,
      matches: [
        {
          jobId: "J-00142",
          title: "Senior Backend Engineer",
          company: "Novable GmbH",
          city: "Berlin",
          country: "DE",
          salary: { min: 85000, max: 102000, currency: "EUR" },
          score: 0.91,
          seniority: "senior",
          visaSponsorship: true,
          remoteOk: false,
          rank: 1,
          strengths: [
            "Matches your 7 years of backend experience",
            "Visa sponsorship confirmed for non-EU candidates",
            "Pay band exceeds your target salary",
          ],
          gaps: ["Onsite only — no hybrid option"],
          why: "Top match on role seniority, salary fit, and visa sponsorship. Slight location preference mismatch.",
        },
        {
          jobId: "J-00167",
          title: "Platform Engineer",
          company: "Meridian Labs",
          city: "Amsterdam",
          country: "NL",
          salary: { min: 78000, max: 95000, currency: "EUR" },
          score: 0.84,
          seniority: "senior",
          visaSponsorship: true,
          remoteOk: true,
          rank: 2,
          strengths: [
            "Hybrid arrangement matches your preference",
            "Highly Skilled Migrant scheme eligible",
            "Team language is English",
          ],
          gaps: ["Pay sits mid-range against your target"],
          why: "Excellent visa path and work style alignment. Salary is adequate but not premium.",
        },
        {
          jobId: "J-00189",
          title: "Backend Engineer, Payments",
          company: "Arcadia Bank",
          city: "Berlin",
          country: "DE",
          salary: { min: 82000, max: 96000, currency: "EUR" },
          score: 0.78,
          seniority: "senior",
          visaSponsorship: true,
          remoteOk: false,
          rank: 3,
          strengths: ["Regulated industry — stable employer", "Relocation package standard"],
          gaps: ["Requires prior payments or fintech exposure"],
          why: "Strong employer quality, mid-range pay, modest skill gap in domain.",
        },
      ],
    },
    relocation: {
      status: "ok",
      score: 0.71,
      summary: "Germany narrowly leads the Netherlands on family and stability.",
      confidence: 0.78,
      top: {
        country: "DE",
        city: "Berlin",
        overall: 0.74,
        dimensions: [
          {
            name: "housing",
            score: 0.54,
            evidence: ["Rental vacancy near 2%", "Deposits: ~3 months"],
          },
          {
            name: "transport",
            score: 0.88,
            evidence: ["U/S-Bahn network top-tier", "Two international airports"],
          },
          {
            name: "healthcare",
            score: 0.82,
            evidence: ["Public system, English support moderate"],
          },
          {
            name: "lifestyle",
            score: 0.76,
            evidence: ["Climate shift manageable", "Strong social safety net"],
          },
          {
            name: "family",
            score: 0.7,
            evidence: ["International schools available", "Spouse work visa supported"],
          },
        ],
        frictions: [
          {
            code: "HOUSING_TIGHT_MARKET",
            severity: "high",
            note: "Long search times typical in Berlin; plan 6–10 weeks.",
          },
          {
            code: "BANKING_HURDLES",
            severity: "medium",
            note: "Bank account typically requires registered address first.",
          },
        ],
      },
      destinations: [
        {
          country: "DE",
          city: "Berlin",
          overall: 0.74,
          dimensions: [],
          frictions: [],
        },
        {
          country: "NL",
          city: "Amsterdam",
          overall: 0.71,
          dimensions: [],
          frictions: [],
        },
      ],
      comparisonNotes: [
        "Germany edges ahead on job volume for senior backend roles.",
        "Netherlands leads on English workplace fluency.",
        "Housing is tight in both markets; Berlin slightly worse.",
      ],
    },
    financial: {
      status: "ok",
      score: 0.79,
      summary:
        "A healthy monthly surplus after taxes; runway comfortably clears the relocation buffer.",
      confidence: 0.81,
      salaryVsCost: 1.34,
      monthlyCost: {
        rent: { amount: 1650, currency: "USD" },
        food: { amount: 520, currency: "USD" },
        transport: { amount: 110, currency: "USD" },
        utilities: { amount: 240, currency: "USD" },
        healthcare: { amount: 380, currency: "USD" },
        other: { amount: 450, currency: "USD" },
        total: { amount: 3350, currency: "USD" },
      },
      monthlySurplus: { amount: 1640, currency: "USD" },
      runwayMonths: 14,
      affordabilityBand: "comfortable",
      relocationCostTotal: { amount: 11200, currency: "USD" },
      assumptions: [
        "Effective tax + social contribution rate modelled at 38%.",
        "Savings assumed at six months of current net salary.",
        "Initial deposit modelled at three months of rent.",
      ],
    },
    documents: {
      status: "ok",
      score: 0.61,
      summary:
        "Most identity and financial documents are in order. Two apostille items are blocking.",
      confidence: 0.9,
      readinessPct: 61,
      blockingMissing: ["degree_apostille", "passport"],
      expiringSoon: ["passport"],
      items: [
        {
          docId: "passport",
          label: "Passport",
          category: "identity",
          status: "expiring",
          requiredFor: ["EU Blue Card"],
          expiresOn: "2026-11-04",
          howToObtain: "Begin renewal at the Indian passport office; allow 6–8 weeks.",
        },
        {
          docId: "degree_apostille",
          label: "Apostilled bachelor's degree",
          category: "education",
          status: "missing",
          requiredFor: ["EU Blue Card"],
          howToObtain: "Submit original degree for apostille via MEA.",
        },
        {
          docId: "employment_letter",
          label: "Current employment letter",
          category: "employment",
          status: "ok",
          requiredFor: ["EU Blue Card"],
        },
        {
          docId: "bank_statements_6m",
          label: "Six months of bank statements",
          category: "financial",
          status: "ok",
          requiredFor: ["EU Blue Card", "Address registration"],
        },
        {
          docId: "marriage_certificate",
          label: "Marriage certificate",
          category: "residence",
          status: "required",
          requiredFor: ["Dependent visa"],
        },
        {
          docId: "police_clearance",
          label: "Police clearance certificate",
          category: "identity",
          status: "required",
          requiredFor: ["EU Blue Card"],
        },
      ],
    },
    timeline: {
      status: "ok",
      score: 0.73,
      summary: "A six-month plan remains feasible if document work starts in the next two weeks.",
      confidence: 0.77,
      earliestMoveDate: "2026-10-18",
      latestMoveDate: "2026-12-06",
      totalWeeks: 26,
      criticalPath: ["passport_renewal", "degree_apostille", "visa_application", "housing_search"],
      milestones: [
        {
          milestoneId: "passport_renewal",
          title: "Renew passport",
          category: "DOCUMENT",
          dependsOn: [],
          earliestStart: "2026-04-28",
          earliestFinish: "2026-06-23",
          durationDays: 56,
          critical: true,
          status: "not_started",
        },
        {
          milestoneId: "degree_apostille",
          title: "Apostille bachelor's degree",
          category: "DOCUMENT",
          dependsOn: [],
          earliestStart: "2026-04-28",
          earliestFinish: "2026-06-02",
          durationDays: 35,
          critical: true,
          status: "not_started",
        },
        {
          milestoneId: "offer_acceptance",
          title: "Accept job offer",
          category: "JOB",
          dependsOn: [],
          earliestStart: "2026-05-20",
          earliestFinish: "2026-06-03",
          durationDays: 14,
          critical: false,
          status: "not_started",
        },
        {
          milestoneId: "visa_application",
          title: "EU Blue Card application",
          category: "VISA",
          dependsOn: ["passport_renewal", "degree_apostille", "offer_acceptance"],
          earliestStart: "2026-06-23",
          earliestFinish: "2026-09-01",
          durationDays: 70,
          critical: true,
          status: "not_started",
        },
        {
          milestoneId: "housing_search",
          title: "Secure Berlin housing",
          category: "HOUSING",
          dependsOn: ["visa_application"],
          earliestStart: "2026-08-15",
          earliestFinish: "2026-10-10",
          durationDays: 56,
          critical: true,
          status: "not_started",
        },
        {
          milestoneId: "move",
          title: "Arrive in Berlin",
          category: "MOVE",
          dependsOn: ["housing_search", "visa_application"],
          earliestStart: "2026-10-15",
          earliestFinish: "2026-10-18",
          durationDays: 3,
          critical: true,
          status: "not_started",
        },
      ],
    },
    cultural: {
      status: "ok",
      score: 0.68,
      summary: "Workplace and administrative culture will require modest adaptation.",
      confidence: 0.7,
      country: "DE",
      languageBasics: [
        { phrase: "Guten Tag", translation: "Good day", context: "formal greeting" },
        { phrase: "Termin", translation: "Appointment", context: "scheduling" },
        { phrase: "Anmeldung", translation: "Address registration", context: "arrival" },
        { phrase: "Bitte", translation: "Please", context: "polite request" },
        { phrase: "Danke schön", translation: "Thank you", context: "courtesy" },
      ],
      workplaceEtiquette: [
        {
          topic: "meetings",
          do: ["Arrive 2–3 minutes early", "Follow agendas closely"],
          dont: ["Be late", "Interrupt during points"],
        },
        {
          topic: "hierarchy",
          do: ["Use Herr/Frau until invited to first names"],
          dont: ["Assume casual tone by default"],
        },
      ],
      socialEtiquette: [
        {
          topic: "public",
          do: ["Keep voices measured in trains", "Separate recycling carefully"],
          dont: ["Cross red pedestrian signals", "Make loud calls indoors"],
        },
      ],
      communicationStyle:
        "Direct, low-context communication is the norm; Germans value clarity over politeness cushions and expect the same in return.",
      firstWeek: [
        { day: 1, task: "Register your address (Anmeldung)", whyItMatters: "Gates bank, tax, and contract access." },
        { day: 2, task: "Open a bank account", whyItMatters: "Needed for salary and rent transfers." },
        { day: 3, task: "Activate public health insurance", whyItMatters: "Mandatory within the first weeks." },
        { day: 4, task: "Request tax ID (Steuer-ID)", whyItMatters: "Required by your employer for payroll." },
        { day: 5, task: "Set up internet and mobile", whyItMatters: "Some contracts require existing German address." },
        { day: 6, task: "Buy a transport pass", whyItMatters: "Cheaper monthly than per-ride." },
        { day: 7, task: "Introduce yourself to neighbours (Hausordnung)", whyItMatters: "House rules matter — quiet hours in particular." },
      ],
      dosAndDonts: [
        "Do pay in cash where expected — still common.",
        "Do separate recycling carefully.",
        "Don't schedule calls or noisy work on Sundays.",
        "Don't expect shops open past 20:00 or on Sundays.",
      ],
    },
  },
  createdAt: new Date(Date.now() - 3 * 86400_000).toISOString(),
  updatedAt: new Date().toISOString(),
};

export const MOCK_CASE_LIST: Array<
  Pick<CaseEnvelope, "caseId" | "status" | "createdAt" | "updatedAt"> & {
    headline: string;
    target: string;
    verdict: string;
  }
> = [
  {
    caseId: "RL-00427",
    status: "ok",
    createdAt: "2026-04-18T10:12:00Z",
    updatedAt: new Date().toISOString(),
    headline: "Berlin within 6 months · EU Blue Card",
    target: "Germany · Berlin",
    verdict: "go_with_caveats",
  },
  {
    caseId: "RL-00391",
    status: "partial",
    createdAt: "2026-03-24T08:04:00Z",
    updatedAt: "2026-04-02T11:20:00Z",
    headline: "Amsterdam · Highly Skilled Migrant",
    target: "Netherlands · Amsterdam",
    verdict: "delay",
  },
  {
    caseId: "RL-00284",
    status: "archived",
    createdAt: "2026-01-06T14:40:00Z",
    updatedAt: "2026-01-12T09:12:00Z",
    headline: "Lisbon · D7 residence exploration",
    target: "Portugal · Lisbon",
    verdict: "reconsider",
  },
];

export function makeMockProgress(): ProgressSnapshot {
  return {
    caseId: "RL-00427",
    overallStatus: "running",
    stages: [
      { stage: "intake", status: "ok" },
      { stage: "intent", status: "ok" },
      { stage: "job", status: "running" },
      { stage: "relocation", status: "pending" },
      { stage: "financial", status: "pending" },
      { stage: "document", status: "pending" },
      { stage: "cultural", status: "pending" },
      { stage: "timeline", status: "pending" },
      { stage: "recommendation", status: "pending" },
      { stage: "summary", status: "pending" },
    ],
  };
}
